

[MacroFactor]
arch              = "arm64-v8a"
patches-source    = "lennyRBLX/apk-patches"
uptodown-dlurl    = "https://macrofactor-diet-sidekick-and-macro-tracker.en.uptodown.com"

# ============================================================
# Disabled / Unused Apps
# ============================================================

# [X]
# patches-source       = "crimera/piko"
# integrations-source  = "crimera/revanced-integrations"
# uptodown-dlurl       = "https://twitter.en.uptodown.com/android"
# apkmirror-dlurl      = "https://www.apkmirror.com/apk/x-corp/twitter"
# archive-dlurl        = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
# version              = "10.49.0-release.0"
